{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "cec55d0b-ff8b-4be0-b32b-842a78d0ca6b",
   "metadata": {},
   "source": [
    "## Q1. Explain why we have to use the Exception class while creating a Custom Exception."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4a0c38ef-d318-427a-9763-2506e00d82a8",
   "metadata": {},
   "source": [
    "## Answer: Using the Exception class as the base for custom exceptions ensures consistency, allows for standard error handling, organizes exceptions in a hierarchy, conveys clear intention, and ensures compatibility with existing code."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "36bfed95-cf1e-4eaa-92b7-002470205c41",
   "metadata": {},
   "source": [
    "## Q2. Write a python program to print Python Exception Hierarchy."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "382f02dc-1240-4e0e-a368-56de27116b81",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Python Exception Hierarchy:\n",
      "BaseException\n",
      "  Exception\n",
      "    TypeError\n",
      "      FloatOperation\n",
      "      MultipartConversionError\n",
      "    StopAsyncIteration\n",
      "    StopIteration\n",
      "    ImportError\n",
      "      ModuleNotFoundError\n",
      "      ZipImportError\n",
      "    OSError\n",
      "      ConnectionError\n",
      "        BrokenPipeError\n",
      "        ConnectionAbortedError\n",
      "        ConnectionRefusedError\n",
      "        ConnectionResetError\n",
      "          RemoteDisconnected\n",
      "      BlockingIOError\n",
      "      ChildProcessError\n",
      "      FileExistsError\n",
      "      FileNotFoundError\n",
      "      IsADirectoryError\n",
      "      NotADirectoryError\n",
      "      InterruptedError\n",
      "        InterruptedSystemCall\n",
      "      PermissionError\n",
      "      ProcessLookupError\n",
      "      TimeoutError\n",
      "      UnsupportedOperation\n",
      "      itimer_error\n",
      "      herror\n",
      "      gaierror\n",
      "      SSLError\n",
      "        SSLCertVerificationError\n",
      "        SSLZeroReturnError\n",
      "        SSLWantWriteError\n",
      "        SSLWantReadError\n",
      "        SSLSyscallError\n",
      "        SSLEOFError\n",
      "      Error\n",
      "        SameFileError\n",
      "      SpecialFileError\n",
      "      ExecError\n",
      "      ReadError\n",
      "      URLError\n",
      "        HTTPError\n",
      "        ContentTooShortError\n",
      "      BadGzipFile\n",
      "    EOFError\n",
      "      IncompleteReadError\n",
      "    RuntimeError\n",
      "      RecursionError\n",
      "      NotImplementedError\n",
      "        ZMQVersionError\n",
      "        StdinNotImplementedError\n",
      "      _DeadlockError\n",
      "      BrokenBarrierError\n",
      "      BrokenExecutor\n",
      "        BrokenThreadPool\n",
      "      SendfileNotAvailableError\n",
      "      ExtractionError\n",
      "      VariableError\n",
      "    NameError\n",
      "      UnboundLocalError\n",
      "    AttributeError\n",
      "      FrozenInstanceError\n",
      "    SyntaxError\n",
      "      IndentationError\n",
      "        TabError\n",
      "    LookupError\n",
      "      IndexError\n",
      "      KeyError\n",
      "        NoSuchKernel\n",
      "        UnknownBackend\n",
      "      CodecRegistryError\n",
      "    ValueError\n",
      "      UnicodeError\n",
      "        UnicodeEncodeError\n",
      "        UnicodeDecodeError\n",
      "        UnicodeTranslateError\n",
      "      UnsupportedOperation\n",
      "      JSONDecodeError\n",
      "      SSLCertVerificationError\n",
      "      Error\n",
      "      UnsupportedDigestmodError\n",
      "      IllegalMonthError\n",
      "      IllegalWeekdayError\n",
      "      ParserError\n",
      "      ClassNotFound\n",
      "      ClipboardEmpty\n",
      "      MessageDefect\n",
      "        NoBoundaryInMultipartDefect\n",
      "        StartBoundaryNotFoundDefect\n",
      "        CloseBoundaryNotFoundDefect\n",
      "        FirstHeaderLineIsContinuationDefect\n",
      "        MisplacedEnvelopeHeaderDefect\n",
      "        MissingHeaderBodySeparatorDefect\n",
      "        MultipartInvariantViolationDefect\n",
      "        InvalidMultipartContentTransferEncodingDefect\n",
      "        UndecodableBytesDefect\n",
      "        InvalidBase64PaddingDefect\n",
      "        InvalidBase64CharactersDefect\n",
      "        InvalidBase64LengthDefect\n",
      "        HeaderDefect\n",
      "          InvalidHeaderDefect\n",
      "          HeaderMissingRequiredValue\n",
      "          NonPrintableDefect\n",
      "          ObsoleteHeaderDefect\n",
      "          NonASCIILocalPartDefect\n",
      "          InvalidDateDefect\n",
      "      MacroToEdit\n",
      "      InvalidFileException\n",
      "      UnequalIterablesError\n",
      "      InvalidVersion\n",
      "      _InvalidELFFileHeader\n",
      "      InvalidWheelFilename\n",
      "      InvalidSdistFilename\n",
      "      InvalidSpecifier\n",
      "      InvalidMarker\n",
      "      UndefinedComparison\n",
      "      UndefinedEnvironmentName\n",
      "      InvalidRequirement\n",
      "        RequirementParseError\n",
      "      InvalidVersion\n",
      "    AssertionError\n",
      "    ArithmeticError\n",
      "      FloatingPointError\n",
      "      OverflowError\n",
      "      ZeroDivisionError\n",
      "        DivisionByZero\n",
      "        DivisionUndefined\n",
      "      DecimalException\n",
      "        Clamped\n",
      "        Rounded\n",
      "          Underflow\n",
      "          Overflow\n",
      "        Inexact\n",
      "          Underflow\n",
      "          Overflow\n",
      "        Subnormal\n",
      "          Underflow\n",
      "        DivisionByZero\n",
      "        FloatOperation\n",
      "        InvalidOperation\n",
      "          ConversionSyntax\n",
      "          DivisionImpossible\n",
      "          DivisionUndefined\n",
      "          InvalidContext\n",
      "    SystemError\n",
      "      CodecRegistryError\n",
      "    ReferenceError\n",
      "    MemoryError\n",
      "    BufferError\n",
      "    Warning\n",
      "      UserWarning\n",
      "        GetPassWarning\n",
      "        FormatterWarning\n",
      "      EncodingWarning\n",
      "      DeprecationWarning\n",
      "        ProvisionalWarning\n",
      "      PendingDeprecationWarning\n",
      "      SyntaxWarning\n",
      "      RuntimeWarning\n",
      "        ProactorSelectorThreadWarning\n",
      "        UnknownTimezoneWarning\n",
      "        PEP440Warning\n",
      "      FutureWarning\n",
      "        ProvisionalCompleterWarning\n",
      "      ImportWarning\n",
      "      UnicodeWarning\n",
      "      BytesWarning\n",
      "      ResourceWarning\n",
      "      DeprecatedTzFormatWarning\n",
      "      PkgResourcesDeprecationWarning\n",
      "    _OptionError\n",
      "    _Error\n",
      "    error\n",
      "    Verbose\n",
      "    Error\n",
      "    SubprocessError\n",
      "      CalledProcessError\n",
      "      TimeoutExpired\n",
      "    TokenError\n",
      "    StopTokenizing\n",
      "    ClassFoundException\n",
      "    EndOfBlock\n",
      "    TraitError\n",
      "    Error\n",
      "    Error\n",
      "      CancelledError\n",
      "      TimeoutError\n",
      "      InvalidStateError\n",
      "    _GiveupOnSendfile\n",
      "    error\n",
      "    Incomplete\n",
      "    TimeoutError\n",
      "    InvalidStateError\n",
      "    LimitOverrunError\n",
      "    QueueEmpty\n",
      "    QueueFull\n",
      "    Empty\n",
      "    Full\n",
      "    ArgumentError\n",
      "    ZMQBaseError\n",
      "      ZMQError\n",
      "        ContextTerminated\n",
      "        Again\n",
      "        InterruptedSystemCall\n",
      "      ZMQBindError\n",
      "      NotDone\n",
      "    PickleError\n",
      "      PicklingError\n",
      "      UnpicklingError\n",
      "    _Stop\n",
      "    ArgumentError\n",
      "    ArgumentTypeError\n",
      "    ConfigError\n",
      "      ConfigLoaderError\n",
      "        ArgumentError\n",
      "      ConfigFileNotFound\n",
      "    ConfigurableError\n",
      "      MultipleInstanceError\n",
      "    ApplicationError\n",
      "    error\n",
      "    TimeoutError\n",
      "    error\n",
      "    ReturnValueIgnoredError\n",
      "    KeyReuseError\n",
      "    UnknownKeyError\n",
      "    LeakedCallbackError\n",
      "    BadYieldError\n",
      "    ReturnValueIgnoredError\n",
      "    Return\n",
      "    InvalidPortNumber\n",
      "    error\n",
      "    LZMAError\n",
      "    RegistryError\n",
      "    _GiveupOnFastCopy\n",
      "    Error\n",
      "      NoSectionError\n",
      "      DuplicateSectionError\n",
      "      DuplicateOptionError\n",
      "      NoOptionError\n",
      "      InterpolationError\n",
      "        InterpolationMissingOptionError\n",
      "        InterpolationSyntaxError\n",
      "        InterpolationDepthError\n",
      "      ParsingError\n",
      "        MissingSectionHeaderError\n",
      "    NoIPAddresses\n",
      "    BadZipFile\n",
      "    LargeZipFile\n",
      "    BadEntryPoint\n",
      "    NoSuchEntryPoint\n",
      "    DuplicateKernelError\n",
      "    ErrorDuringImport\n",
      "    NotOneValueFound\n",
      "    CannotEval\n",
      "    OptionError\n",
      "    BdbQuit\n",
      "    Restart\n",
      "    ExceptionPexpect\n",
      "      EOF\n",
      "      TIMEOUT\n",
      "    PtyProcessError\n",
      "    FindCmdError\n",
      "    HomeDirError\n",
      "    ProfileDirError\n",
      "    IPythonCoreError\n",
      "      TryNext\n",
      "      UsageError\n",
      "      StdinNotImplementedError\n",
      "    InputRejected\n",
      "    GetoptError\n",
      "    ErrorToken\n",
      "    PrefilterError\n",
      "    AliasError\n",
      "      InvalidAliasError\n",
      "    Error\n",
      "      InterfaceError\n",
      "      DatabaseError\n",
      "        InternalError\n",
      "        OperationalError\n",
      "        ProgrammingError\n",
      "        IntegrityError\n",
      "        DataError\n",
      "        NotSupportedError\n",
      "    Warning\n",
      "    SpaceInInput\n",
      "    DOMException\n",
      "      IndexSizeErr\n",
      "      DomstringSizeErr\n",
      "      HierarchyRequestErr\n",
      "      WrongDocumentErr\n",
      "      InvalidCharacterErr\n",
      "      NoDataAllowedErr\n",
      "      NoModificationAllowedErr\n",
      "      NotFoundErr\n",
      "      NotSupportedErr\n",
      "      InuseAttributeErr\n",
      "      InvalidStateErr\n",
      "      SyntaxErr\n",
      "      InvalidModificationErr\n",
      "      NamespaceErr\n",
      "      InvalidAccessErr\n",
      "      ValidationErr\n",
      "    ValidationError\n",
      "    EditReadOnlyBuffer\n",
      "    _Retry\n",
      "    InvalidLayoutError\n",
      "    HeightIsUnknownError\n",
      "    ParserSyntaxError\n",
      "    InternalParseError\n",
      "    _PositionUpdatingFinished\n",
      "    SimpleGetItemNotFound\n",
      "    UncaughtAttributeError\n",
      "    HasNoContext\n",
      "    ParamIssue\n",
      "    _JediError\n",
      "      InternalError\n",
      "      WrongVersion\n",
      "      RefactoringError\n",
      "    OnErrorLeaf\n",
      "    InvalidPythonEnvironment\n",
      "    MessageError\n",
      "      MessageParseError\n",
      "        HeaderParseError\n",
      "        BoundaryError\n",
      "      MultipartConversionError\n",
      "      CharsetError\n",
      "    Error\n",
      "    HTTPException\n",
      "      NotConnected\n",
      "      InvalidURL\n",
      "      UnknownProtocol\n",
      "      UnknownTransferEncoding\n",
      "      UnimplementedFileMode\n",
      "      IncompleteRead\n",
      "      ImproperConnectionState\n",
      "        CannotSendRequest\n",
      "        CannotSendHeader\n",
      "        ResponseNotReady\n",
      "      BadStatusLine\n",
      "        RemoteDisconnected\n",
      "      LineTooLong\n",
      "    InteractivelyDefined\n",
      "    KillEmbedded\n",
      "    Error\n",
      "      NoSuchProcess\n",
      "        ZombieProcess\n",
      "      AccessDenied\n",
      "      TimeoutExpired\n",
      "    _Ipv6UnsupportedError\n",
      "    QueueEmpty\n",
      "    QueueFull\n",
      "    DebuggerInitializationError\n",
      "    ExpatError\n",
      "    Error\n",
      "      ProtocolError\n",
      "      ResponseError\n",
      "      Fault\n",
      "    ParseBaseException\n",
      "      ParseException\n",
      "      ParseFatalException\n",
      "        ParseSyntaxException\n",
      "    RecursiveGrammarException\n",
      "    ResolutionError\n",
      "      VersionConflict\n",
      "        ContextualVersionConflict\n",
      "      DistributionNotFound\n",
      "      UnknownExtra\n",
      "    _Error\n",
      "    UnableToResolveVariableException\n",
      "    InvalidTypeInArgsException\n",
      "  GeneratorExit\n",
      "  SystemExit\n",
      "  KeyboardInterrupt\n",
      "  CancelledError\n",
      "  AbortThread\n"
     ]
    }
   ],
   "source": [
    "def print_exception_hierarchy(exception_class, indent=0):\n",
    "    print(\" \" * indent + str(exception_class.__name__))\n",
    "    for subclass in exception_class.__subclasses__():\n",
    "        print_exception_hierarchy(subclass, indent + 2)\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    print(\"Python Exception Hierarchy:\")\n",
    "    print_exception_hierarchy(BaseException)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "62b5498c-21fb-4301-9bca-0287751e28d0",
   "metadata": {},
   "source": [
    "##  Q3. What errors are defined in the ArithmeticError class? Explain any two with an example."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "795efc7f-9b04-4a83-bde8-74a94f9ae090",
   "metadata": {},
   "outputs": [],
   "source": [
    "The ArithmeticError class is the base class for arithmetic-related exceptions in Python. It represents errors \n",
    "that occur during arithmetic operations. Some common errors defined in the ArithmeticError class include:\n",
    "\n",
    "ZeroDivisionError: This error occurs when attempting to divide a number by zero.\n",
    "Example:\n",
    "\n",
    "def divide_numbers(a, b):\n",
    "    try:\n",
    "        result = a / b\n",
    "        return result\n",
    "    except ZeroDivisionError as e:\n",
    "        print(f\"Error: {e}\")\n",
    "        return None\n",
    "\n",
    "numerator = 10\n",
    "denominator = 0\n",
    "OverflowError: This error occurs when the result of an arithmetic operation exceeds the maximum representable value for\n",
    "a numeric data type.\n",
    "Example:\n",
    "\n",
    "def calculate_factorial(n):\n",
    "    try:\n",
    "        result = 1\n",
    "        for i in range(1, n+1):\n",
    "            result *= i\n",
    "        return result\n",
    "    except OverflowError as e:\n",
    "        print(f\"Error: {e}\")\n",
    "        return None\n",
    "\n",
    "number = 1000\n",
    "factorial = calculate_factorial(number)\n",
    "print(\"Factorial:\", factorial)\n",
    "In this example, we attempt to calculate the factorial of a large number (number = 1000).\n",
    "However, the result of the calculation exceeds the maximum value representable by the int data type, leading to an OverflowError.\n",
    "The program handles the error using a try-except block, and the code inside the except block is executed, printing the error message. \n",
    "The result of the factorial calculation is set to None since the result is not valid due to the overflow."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7abe8970-467f-4c43-bfc1-384a76060834",
   "metadata": {},
   "source": [
    "## Q4. Why LookupError class is used? Explain with an example KeyError and IndexError."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f5ee6739-17ae-475b-b2e4-65da5c82774e",
   "metadata": {},
   "outputs": [],
   "source": [
    "The LookupError class is a base class for exceptions that occur when a lookup or indexing operation is performed on a sequence\n",
    "(like lists, tuples, strings) or a mapping (like dictionaries) and the key or index is not found or out of range.\n",
    "\n",
    "Using the LookupError class as a base allows for handling multiple types of lookup-related exceptions in a single catch block, \n",
    "making error handling more concise and robust.\n",
    "\n",
    "KeyError: This exception is raised when trying to access a dictionary key that does not exist.\n",
    "Example:\n",
    "\n",
    "my_dict = {\"apple\": 1, \"banana\": 2, \"orange\": 3}\n",
    "\n",
    "try:\n",
    "    value = my_dict[\"grape\"]\n",
    "except KeyError as e:\n",
    "    print(f\"Error: {e}\")\n",
    "In this example, we have a dictionary my_dict. When we try to access the key \"grape\", which is not present in the dictionary, \n",
    "a KeyError is raised. The program handles the error using a try-except block, and the code inside the except block is executed,\n",
    "printing the error message.\n",
    "\n",
    "IndexError: This exception is raised when trying to access a sequence (like a list or tuple) with an invalid index, either too\n",
    "large or too small.\n",
    "Example:\n",
    "\n",
    "my_list = [1, 2, 3, 4]\n",
    "\n",
    "try:\n",
    "    value = my_list[5]\n",
    "except IndexError as e:\n",
    "    print(f\"Error: {e}\")\n",
    "In this example, we have a list my_list. When we try to access the element at index 5, which is out of range for the list \n",
    "(valid indices are from 0 to len(my_list)-1), an IndexError is raised. The program handles the error using a try-except block,\n",
    "and the code inside the except block is executed, printing the error message.\n",
    "\n",
    "Using LookupError as the base class allows you to catch both KeyError and IndexError (and any other subclass of LookupError)\n",
    "in a single exception handler, providing a more generic and concise approach to handle lookup-related errors."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "3261a409-19c1-476a-9d51-22740387f86b",
   "metadata": {},
   "source": [
    "## Q5. Explain ImportError. What is ModuleNotFoundError?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ded4aba3-b213-4317-ae8c-1b893e71fdc6",
   "metadata": {},
   "outputs": [],
   "source": [
    "Ans -> ImportError is an exception class in Python that is raised when there is an error during the process of importing a module. This can happen due to various reasons, such as a missing module, a module that cannot be found, or an issue within the module itself.\n",
    "\n",
    "Example of ImportError: Let's say we have a file named my_module.py, and it contains the following code:\n",
    "\n",
    "# my_module.py\n",
    "print(\"Hello from my_module!\")\n",
    "\n",
    "def my_function():\n",
    "    return \"This is my_function inside my_module.\"\n",
    "Now, let's try to import this module and call the function from another Python script:\n",
    "\n",
    "# main.py\n",
    "try:\n",
    "    import my_module\n",
    "    print(my_module.my_function())\n",
    "except ImportError as e:\n",
    "    print(f\"ImportError: {e}\")\n",
    "If my_module.py is in the same directory as main.py, everything will work correctly, and the output will be:\n",
    "\n",
    "Hello from my_module!\n",
    "This is my_function inside my_module.\n",
    "However, if my_module.py is not found or not in the correct path, an ImportError will be raised with the appropriate error message.\n",
    "\n",
    "ModuleNotFoundError is a subclass of ImportError introduced in Python 3.6. It is specifically raised when a module cannot be found during the import process. This error indicates that Python could not locate the module specified in the import statement.\n",
    "\n",
    "Example of ModuleNotFoundError:\n",
    "\n",
    "Let's assume some_module.py does not exist. If we try to import it in a Python script:\n",
    "\n",
    "# main.py\n",
    "try:\n",
    "    import some_module\n",
    "except ModuleNotFoundError as e:\n",
    "    print(f\"ModuleNotFoundError: {e}\")\n",
    "The output will be:\n",
    "\n",
    "ModuleNotFoundError: No module named 'some_module'\n",
    "In this case, ModuleNotFoundError is raised because Python cannot find the module named some_module and reports it accordingly.\n",
    "\n",
    "To summarize, ImportError is raised when there is an error during module import, while ModuleNotFoundError is a specific subclass of ImportError raised when a module cannot be found during the import process."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "70ffb804-156f-4037-85e7-eedb14cd5a67",
   "metadata": {},
   "source": [
    "## Q6. List down some best practices for exception handling in python."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fa5ef172-4d36-46c8-ad99-a967cdcccf9a",
   "metadata": {},
   "outputs": [],
   "source": [
    " Exception handling is an essential aspect of writing robust and maintainable code in Python. Here are some best practices for\n",
    "    exception handling:\n",
    "\n",
    "Use Specific Exceptions: Catch specific exceptions rather than using broad except blocks. This allows you to handle different errors\n",
    "differently and avoids catching unintended exceptions.\n",
    "\n",
    "Keep Exception Blocks Small: Limit the code within the try-except block to only the statements that may raise the expected exception.\n",
    "This helps in pinpointing the cause of the exception.\n",
    "\n",
    "Avoid Empty Except Blocks: Avoid using empty except blocks as they hide the error details and make debugging challenging. \n",
    "Always include informative error messages or logging to understand the cause of the exception.\n",
    "\n",
    "Use Multiple Except Blocks: When handling multiple exceptions, use separate except blocks for each exception to provide targeted error\n",
    "handling.\n",
    "\n",
    "Use finally Block: Use the finally block to execute code that must be executed, whether an exception occurs or not. Commonly used for\n",
    "cleanup tasks.\n",
    "\n",
    "Avoid Catching Base Exception: Avoid catching the base Exception class directly, as it may lead to catching unexpected and\n",
    "potentially harmful exceptions. Catch specific exceptions instead.\n",
    "\n",
    "Use Exception Chaining: If you need to handle an exception but still want to propagate it, use raise without any arguments \n",
    "inside the except block to re-raise the original exception with the complete traceback.\n",
    "\n",
    "Handle Exceptions Locally: Handle exceptions as close to the point of occurrence as possible. Avoid handling exceptions too far \n",
    "away from where they occur, as it can make debugging and code maintenance difficult."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
